### PR TITLE
Add smooth camera movement

### PR DESCRIPTION
**Pull request by xordspar0**
When connecting a part to a structure, the camera moves to that structure while doing the build action. Now that camera movement is linearly interpolated.

This is more work on #351.

Issues:
- [x] The camera never moves back after building
- [ ] I'm not sure about the hacky event system; it's just a quick thing I added to solve the problem
- [x] Code cleanup, commented code, etc.
- [x] Probably doesn't need a lume dependency
- [x] The animation speed is dependent of frame rate
- [x] Angles are not bounded to 0-360 degrees
- [x] The linear interpolation is from current position to target position instead of from starting position to target position. This makes the animation look nonlinear and go faster than expected.

### CODE REVIEW

**Comment by xordspar0** [comment]
[Screencast from 2024-04-18 17-14-40.webm](https://github.com/synthein/synthein/assets/2390950/eba3159c-17d0-4828-962c-513a6295bbb2)

**Comment by xordspar0** [comment]
[Screencast from 2024-04-18 17-24-14.webm](https://github.com/synthein/synthein/assets/2390950/81b60d2c-0de7-4f2a-89db-5eba7ff6f811)

**Review by randomguyeatspotato — APPROVED** [review]

**Comment by xordspar0** [comment]
I'm still not sure about the best solution to the event thing, but this works, I can't think of something better, and the damage is limited to the selection.lua and camera.lua.

**Review by randomguyeatspotato — APPROVED** [review]
Looks good like the improvements. Makes the game better.

**Pull request merged**
