### PR TITLE
Automatic packaging for Linux, Mac and Windows

### PR DESCRIPTION
**Pull request by xordspar0**
This is part of #58.

### CODE REVIEW

**Comment by xordspar0** [comment]
I didn't end up doing AppImages because building them inside Docker has several problems. I didn't do snaps or Flatpaks yet because that will take a significantly larger amount of work than any of they other formats, plus they involve uploading to a repository that allows automatic updates. That's really cool, but I don't feel confident enabling that yet.

**Comment by xordspar0** [comment]
Well, what do you think? Should we merge it?

**Comment by probonopd** [comment]
> I didn't end up doing AppImages because building them inside Docker has several problems. 

Can you elaborate please? Many projects, including Kdevelop and Krita, build AppImages inside Docker.

**Comment by xordspar0** [comment]
Oh, really? I would love to distribute this as an AppImage. Here are the problems I ran into:

- My project is a LÖVE game. The documentation of LÖVE recommends using **care** from reproducible.io to collect dependencies. Unfortunately, care uses ptrace, which doesn't seem to be available inside Docker.
- I wasn't able to get appimagetool to run in my Docker container because AppImages use FUSE, which also doesn't seem to be available in (unprivileged) Docker containers. (I might be wrong about that.)

Thanks for pointing out that Kdevelop and Krita already do this. I will take a look at how those projects do it.

**Comment by probonopd** [comment]
I don't know about why you need Docker and couldn't bulid LÖVE games on Travis CI directly. In any case, you can use `--appimage-extract` to unpack the contents of (type 2) AppImages such as the appimagetool one on systems where FUSE is not available.

**Comment by xordspar0** [comment]
I'm not familiar with Travis CI. I'm using Drone, which does all of its builds in Docker containers.

**Comment by probonopd** [comment]
Any chance there will be an AppImage for download anytime soon on GitHub Releases? Thanks.

**Comment by xordspar0** [comment]
I haven't looked at doing AppImages since April, but I'm definitely still interested. I'll take a look soon. I've opened an issue for it: #132.

**Pull request merged**
